version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore PocaPal.API/PocaPal.API.csproj
  build:
    commands:
      - dotnet build PocaPal.API/PocaPal.API.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ PocaPal.API/PocaPal.API.csproj
artifacts:
  files:
    - '**/*'